// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzinmrvmlwksesscymkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6aW5tcnZtbHdrc2Vzc2N5bWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjcwOTYsImV4cCI6MjA2MjU0MzA5Nn0.YgDq1qL_yAjQIhQZoo2amQaD6bOAgjIJKl9mtu7iopo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);